### ISSUE TITLE
not work ur script 

### ISSUE THREAD

**Issue by Zakarto** [Jiroarb/townstar#1]
Hello men,
i activate ur script in Tampermonkey and This script will not draw a button on top left of the game.
can u help me plz!!! 
and i use in browser plugin  the message :
No template found with name Wood_VFX      __game-scripts.js:1 
No template found with name Grapes_VFX          5__game-scripts.js:1 
No template found with name Wood_VFX        2__game-scripts.js:1 
No template found with name Grapes_VFX       __game-scripts.js:1 
No template found with name Gasoline_VFX
ect ect

**Comment by Jiroarb** [comment]
I have no problem with the script. 
The messages have nothing to do with the script.
Please look for userscript.html in the console.
![image](https://user-images.githubusercontent.com/60472727/130206055-25d34368-9046-4688-bcdd-d5cfb8f43ee2.png)
The button will show as per above image

**Comment by Zakarto** [comment]
loook my image 

![image](https://user-images.githubusercontent.com/89228812/130210869-0ed45490-9673-4548-b894-3968a2a2f56f.png)

**Comment by Jiroarb** [comment]
Have you try other script before with Tampermonkey? 
Show me the console part.
![image](https://user-images.githubusercontent.com/60472727/130225137-7da0e880-8904-4a39-9601-fb0c8c109e43.png)

**Comment by Zakarto** [comment]
Ty it works after a chrom reset
