### ISSUE TITLE
Script 

### ISSUE THREAD

**Issue by Zakarto** [Jiroarb/townstar#2]
Hello
I hope you are fine ?
I would like to ask you something if you know yourself a bit on javascript
I would like to change the name "Refinery" by ''' id'''  raffanery  IDentifier
var refineryArray = Object.values(Game.town.objectDict).filter(o => o.type === 'Refinery');
it's possible ???

this is to differentiate the building example: when we have 3 refineries so that I can give each task to do to make each one a predefined object.

**Comment by Jiroarb** [comment]
To get specific building, you need to get the position of the object. 
For example: 
var firstRefinery =  Object.values(Game.town.objectDict).filter(o => o.townX === 25 && o.townZ === 20);
var secondRefinery =  Object.values(Game.town.objectDict).filter(o => o.townX === 20 && o.townZ === 20);

Then you can define what task you want per object.

**Comment by Zakarto** [comment]
what's this townX and TownZ ??? What does she represent
![image](https://user-images.githubusercontent.com/89228812/130355448-5d89618e-961b-4744-a1e7-70cca6822327.png)

 for exemple what is position water_facility in my map

**Comment by Jiroarb** [comment]
You can use Game.town.selectedObject to find townX & townZ.
